# Generated by Django 3.1.3 on 2020-11-15 07:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20201115_1611'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='post',
            new_name='product',
        ),
    ]
