# Generated by Django 3.1.3 on 2020-11-15 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201115_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='p_user',
        ),
    ]
