# Generated by Django 3.1.3 on 2020-11-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_p_user'),
        ('accounts', '0002_auto_20201115_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='buying_order',
            field=models.ManyToManyField(blank=True, to='product.Product'),
        ),
    ]
